if(EXISTS "/home/egor/untitled5/test_integrator[1]_tests.cmake")
  include("/home/egor/untitled5/test_integrator[1]_tests.cmake")
else()
  add_test(test_integrator_NOT_BUILT test_integrator_NOT_BUILT)
endif()
